### ISSUE TITLE
가로모드 일때 사용자에게 보여질 화면 조정!

### ISSUE THREAD

**Issue by jaeryo2357** [naccoro/WASK-Android#111]
![image](https://user-images.githubusercontent.com/33657541/101280294-b6f16080-380b-11eb-9488-9a4ce6631e5e.png)

가로 모드를 지원하고자 한다면 수정해야할 목록인 듯 합니다!

**Comment by ethan-223** [comment]
https://github.com/naccoro/WASK-Android/pull/121
