### ISSUE TITLE
달력에서 월 이동을 위한 picker의 터치 영역을 늘리면 좋겠습니다.

### ISSUE THREAD

**Issue by ethan-223** [naccoro/WASK-Android#64]
![image](https://user-images.githubusercontent.com/57310034/90314766-40291280-df51-11ea-9327-c9fed51a9e36.png)
이 부분이 터치 영역이 너무 작아 잘 안눌려서 패딩 값을 줘서 늘리면 좋을 것 같습니다.

**Comment by euzl** [comment]
넵!̑̈ !̊̈ !̐̈!̑̈ !̊̈ !̐̈ 근데 의문인게 레이아웃영역으로 터치되게했는데 왜 아이콘누르면 터치가 안 되는지 의문...
