### ISSUE TITLE
Android App Bundle - 앱 크기 최적화

### ISSUE THREAD

**Issue by zoonun** [naccoro/WASK-Android#76]

**Comment by zoonun** [comment]
[관련 당근마켓 medium 포스팅](https://medium.com/daangn/%EB%8D%94-%EC%9E%91%EC%9D%80-apk%EB%A5%BC-%EC%9C%84%ED%95%9C-android-app-bundle%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C-345a656eee85)

**Comment by jaeryo2357** [comment]
번들로 올렸습니다!.
